---
- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present

- name: Pull Grafana Docker image
  docker_image:
    name: "{{ grafana_image }}"
    source: pull

- name: Run Grafana container
  docker_container:
    name: "{{ grafana_container_name }}"
    image: "{{ grafana_image }}"
    ports:
      - "{{ grafana_port }}:{{ grafana_port }}"
    state: started
