---
- name: Setup new Debian installation
  hosts: localhost
  gather_facts: true 
  become: true

  roles:
    - install_packages
    - vim_install_config
    - docker_install
    - grafana_docker
    - node_exporter_docker
    - prometheus_docker
