---
- name: Setup new Debian installation
  hosts: localhost
  gather_facts: true 
  become: true

  vars_files:
    - vars.yml

  roles:
    - vim_install_config
    - docker_install
    - grafana_docker
    - node_exporter_docker
    - prometheus_docker
  
  tasks:

    - name: Install required initial packages
      apt:
        name: "{{ packages }}"
        state: present
