---
- name: Setup new Debian installation
  hosts: localhost
  gather_facts: true 
  become: true

  vars_files:
    - vars.yml

  roles:
    - vim_install_config
    - docker_install

  tasks:

    - name: Install required initial packages
      apt:
        name: "{{ packages }}"
        state: present
