---
- name: Setup new Debian installation
  hosts: localhost
  become: true

  vars_files:
    - vars.yml

  tasks:

    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present

