---
- name: Set variable indicating role execution
  set_fact:
    cadvisor_docker_role_executed: true

- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present

- name: Pull Cadvisor Docker image
  docker_image:
    name: "{{ cadvisor_image }}"
    source: pull

- name: Start Cadvisor container
  docker_container:
    name: "{{ cadvisor_container_name }}" 
    image: "{{ cadvisor_image }}" 
    ports:
      - "{{ cadvisor_port }}:{{ cadvisor_port }}"
    state: started
    restart_policy: unless-stopped
    volumes: "{{ cadvisor_volume_mounts }}"
