---
- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present

- name: Build Custom Jenkins Docker image
  command: docker build -t {{ jenkins_image }} {{ jenkins_dockerfile_path }}

- name: Pull Custom Jenkins Docker image
  docker_image:
    name: "{{ jenkins_image }}"
    source: pull

- name: Run Jenkins container
  docker_container:
    name: "{{ jenkins_container_name }}"
    image: "{{ jenkins_image }}"
    ports:
      - "{{ jenkins_port }}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    state: started
    restart_policy: unless-stopped
