---
- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present

- name: Pull Jenkins Docker image
  docker_image:
    name: "{{ jenkins_image }}"
    source: pull

- name: Run Jenkins container
  docker_container:
    name: "{{ jenkins_container_name }}"
    image: "{{ jenkins_image }}"
    ports:
      - "{{ jenkins_port }}:8080"
    state: started
    restart_policy: unless-stopped
