---
- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present

- name: Pull Node Exporter Docker image
  docker_image:
    name: "{{ node_exporter_image }}"
    source: pull

- name: Start Node Exporter container
  docker_container:
    name: "{{ node_exporter_container_name }}"
    image: "{{ node_exporter_image }}"
    ports:
      - "{{ node_exporter_port }}:{{ node_exporter_port }}"
    state: started
